language: python
python: 3.6
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds
    - $HOME/node_modules
    - $HOME/assets/dist
before_install:
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update && sudo apt-get install curl -y
  - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
  - sudo apt install nodejs -y
  - node --version
  - sudo apt-get install yarn -y
install:
  - yarn install
  - pip install -U pip
# Uncomment when new Lektor package is available
# - "pip install Lektor"
  - pip install git+https://github.com/lektor/lektor#egg=Lektor
script: yarn build:prod && lektor build --no-prune
deploy:
  - provider: script
    script: lektor deploy develop
    on:
       branch: develop
  - provider: script
    script: bash scripts/deploy.sh
    on:
       branch: production
